In [4]:
import pandas as pd
pd.__version__

'2.3.3'

# Pandas Data Structure

In [ ]:
Series-- One-dimensional column
DataFrame-- Table with rows+columns

In [6]:
s = pd.Series([10,20,30])
s

0    10
1    20
2    30
dtype: int64

In [7]:
df = pd.DataFrame({
    "name":["Yashmitha","Krishna"],
    "Age":[19,23]
})
df

        name  Age
0  Yashmitha   19
1    Krishna   23

# Reading CSV

In [9]:
df = pd.read_csv(r"C:\Users\yashm\Book1.csv")
df

   Full Name Department   Roll Number
0  yashmitha          IT         1201
1   swanitha        AIML         1202
2   srivalli         CSE         1203

In [5]:
df = pd.read_csv(r"C:\Users\yashm\Downloads\weather_data.csv")
df

         Date          City  Temperature_C  Humidity_% Condition
0  01-01-2025      Hyderbad           28.0        60.0     Sunny
1  02-01-2025    Vijayawada           29.0        62.0     Sunny
2  03-01-2025  Viskhapatnam            NaN        58.0    Cloudy
3  04-01-2025      Kakinada           31.0        55.0    Cloudy
4  05-01-2025      Banglore            NaN        57.0     Rainy
5  06-01-2025        Mumbai           33.0         NaN     Rainy
6  07-01-2025       Chennai           34.0        61.0     Sunny
7  08-01-2025    Rajamundry           32.0        63.0    Cloudy
8  09-01-2025         Eluru            NaN        64.0     Rainy
9  10-01-2025    Anakapalli           29.0        62.0     Sunny

# Reading Data(Excel)

In [29]:
df = pd.read_excel(r"C:\Users\yashm\Downloads\weather_data_XL.xlsx")  # use pip or conda to install excel
df

        Date        City  Temperature_C  Humidity_% Condition
0 2025-01-01    Hyderbad             28          60     Sunny
1 2025-01-02    Hyderbad             29          62     Sunny
2 2025-01-03    Hyderbad             30          58    Cloudy
3 2025-01-04    Hyderbad             31          55    Cloudy
4 2025-01-05    Banglore             32          57     Rainy
5 2025-01-06    Banglore             33          59     Rainy
6 2025-01-07    Banglore             34          61     Sunny
7 2025-01-08    Banglore             32          63    Cloudy
8 2025-01-09  Vijayawada             31          64     Rainy
9 2025-01-10  Vijayawada             29          62     Sunny

# Writing data(Excel)

In [16]:
Student = {
    "name":["Yashmitha","Srivalli","Swanitha","Sindhu","Srinidhi"],
    "Rollno":[1201,1202,1203,1204,1205],
    "Department":["ECE","EEE","CSE","IT","AIML"]
}
df = pd.DataFrame(Student)
df

        name  Rollno Department
0  Yashmitha    1201        ECE
1   Srivalli    1202        EEE
2   Swanitha    1203        CSE
3     Sindhu    1204         IT
4   Srinidhi    1205       AIML

# Writing the data Into Files

In [17]:
df.to_csv('data.csv',index=False)

In [27]:
df.to_excel('new.xlsx',sheet_name = 'weather_data',index=False)

# Exploring Data

In [25]:
df.head()  # First five rows

        Date      City  Temperature_C  Humidity_% Condition
0 2025-01-01  Hyderbad             28          60     Sunny
1 2025-01-02  Hyderbad             29          62     Sunny
2 2025-01-03  Hyderbad             30          58    Cloudy
3 2025-01-04  Hyderbad             31          55    Cloudy
4 2025-01-05  Banglore             32          57     Rainy

In [26]:
df.head(2)

        Date      City  Temperature_C  Humidity_% Condition
0 2025-01-01  Hyderbad             28          60     Sunny
1 2025-01-02  Hyderbad             29          62     Sunny

In [30]:
df.tail(1)            # last 1 row

        Date        City  Temperature_C  Humidity_% Condition
9 2025-01-10  Vijayawada             29          62     Sunny

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Date           10 non-null     datetime64[ns]
 1   City           10 non-null     object
 2   Temperature_C  10 non-null     int64
 3   Humidity_%     10 non-null     int64
 4   Condition      10 non-null     object
dtypes: datetime64[ns](1), int64(2), object(2)
memory usage: 532.0+ bytes

In [35]:
df['Date']    # m1

0   2025-01-01
1   2025-01-02
2   2025-01-03
3   2025-01-04
4   2025-01-05
5   2025-01-06
6   2025-01-07
7   2025-01-08
8   2025-01-09
9   2025-01-10
Name: Date, dtype: datetime64[ns]

In [34]:
df.Date            # m2

0   2025-01-01
1   2025-01-02
2   2025-01-03
3   2025-01-04
4   2025-01-05
5   2025-01-06
6   2025-01-07
7   2025-01-08
8   2025-01-09
9   2025-01-10
Name: Date, dtype: datetime64[ns]

In [36]:
df.shape

(10, 5)

In [37]:
df[4:8]

        Date      City  Temperature_C  Humidity_% Condition
4 2025-01-05  Banglore             32          57     Rainy
5 2025-01-06  Banglore             33          59     Rainy
6 2025-01-07  Banglore             34          61     Sunny
7 2025-01-08  Banglore             32          63    Cloudy

In [38]:
df.columns

Index(['Date', 'City', 'Temperature_C', 'Humidity_%', 'Condition'], dtype='object')

In [39]:
df.index

RangeIndex(start=0, stop=10, step=1)

In [41]:
df.dtypes

Date             datetime64[ns]
City                     object
Temperature_C             int64
Humidity_%                int64
Condition                object
dtype: object

In [42]:
df[['Date','Condition']]

        Date Condition
0 2025-01-01     Sunny
1 2025-01-02     Sunny
2 2025-01-03    Cloudy
3 2025-01-04    Cloudy
4 2025-01-05     Rainy
5 2025-01-06     Rainy
6 2025-01-07     Sunny
7 2025-01-08    Cloudy
8 2025-01-09     Rainy
9 2025-01-10     Sunny

# Missing Values

In [7]:
df.isnull()

    Date   City  Temperature_C  Humidity_%  Condition
0  False  False          False       False      False
1  False  False          False       False      False
2  False  False          False       False      False
3  False  False          False       False      False
4  False  False          False       False      False
5  False  False          False       False      False
6  False  False          False       False      False
7  False  False          False       False      False
8  False  False          False       False      False
9  False  False          False       False      False

In [8]:
df.isnull().sum()

Date             0
City             0
Temperature_C    0
Humidity_%       0
Condition        0
dtype: int64

In [16]:
df = pd.DataFrame({
    "name":["Yashmitha","Swanitha","Srivalli"],
    "Age":[25,23,None]
})
df

        name   Age
0  Yashmitha  25.0
1   Swanitha  23.0
2   Srivalli   NaN

# Handling Missing Values

In [18]:
df['Age'] = df['Age'].fillna(df['Age'].mean())
df

        name   Age
0  Yashmitha  25.0
1   Swanitha  23.0
2   Srivalli  24.0

In [19]:
df_clean = df.dropna()

In [20]:
df_clean

        name   Age
0  Yashmitha  25.0
1   Swanitha  23.0
2   Srivalli  24.0

# Duplicates

In [21]:
df = pd.DataFrame({
    "name":["Yashmitha","Swanitha","Yashmitha"],
    "reg":[1201,1202,1201]
})
df

        name   reg
0  Yashmitha  1201
1   Swanitha  1202
2  Yashmitha  1201

In [22]:
df.duplicated()    # check DuplicateValues

0    False
1    False
2     True
dtype: bool

In [23]:
df = df.drop_duplicates()
df

        name   reg
0  Yashmitha  1201
1   Swanitha  1202

# Statistics

In [38]:
df = pd.read_excel(r"C:\Users\yashm\Downloads\weather_data_XL.xlsx")
df

        Date        City  Temperature_C  Humidity_% Condition
0 2025-01-01    Hyderbad             28          60     Sunny
1 2025-01-02    Hyderbad             29          62     Sunny
2 2025-01-03    Hyderbad             30          58    Cloudy
3 2025-01-04    Hyderbad             31          55    Cloudy
4 2025-01-05    Banglore             32          57     Rainy
5 2025-01-06    Banglore             33          59     Rainy
6 2025-01-07    Banglore             34          61     Sunny
7 2025-01-08    Banglore             32          63    Cloudy
8 2025-01-09  Vijayawada             31          64     Rainy
9 2025-01-10  Vijayawada             29          62     Sunny

In [40]:
df['Temperature_C'].std()

1.911950719959998

In [41]:
df['Temperature_C'].var()

3.6555555555555554

In [42]:
df['Temperature_C'].min()

28

In [43]:
df['Temperature_C'].max()

34

In [44]:
df['Temperature_C'].describe()

count    10.000000
mean     30.900000
std       1.911951
min      28.000000
25%      29.250000
50%      31.000000
75%      32.000000
max      34.000000
Name: Temperature_C, dtype: float64

In [47]:
df.City[df.Temperature_C == df.Temperature_C.max()]

6    Banglore
Name: City, dtype: object

In [48]:
df.count()

Date             10
City             10
Temperature_C    10
Humidity_%       10
Condition        10
dtype: int64

In [49]:
df["City"].nunique()

3

In [51]:
df["City"].value_counts()

City
Hyderbad      4
Banglore      4
Vijayawada    2
Name: count, dtype: int64

# String Cleaning

In [54]:
df

        Date        City  Temperature_C  Humidity_% Condition
0 2025-01-01    hyderbad             28          60     Sunny
1 2025-01-02    hyderbad             29          62     Sunny
2 2025-01-03    hyderbad             30          58    Cloudy
3 2025-01-04    hyderbad             31          55    Cloudy
4 2025-01-05    banglore             32          57     Rainy
5 2025-01-06    banglore             33          59     Rainy
6 2025-01-07    banglore             34          61     Sunny
7 2025-01-08    banglore             32          63    Cloudy
8 2025-01-09  vijayawada             31          64     Rainy
9 2025-01-10  vijayawada             29          62     Sunny

In [59]:
df["City"] = df["City"].str.upper()
df

        Date        City  Temperature_C  Humidity_% Condition
0 2025-01-01    HYDERBAD             28          60     Sunny
1 2025-01-02    HYDERBAD             29          62     Sunny
2 2025-01-03    HYDERBAD             30          58    Cloudy
3 2025-01-04    HYDERBAD             31          55    Cloudy
4 2025-01-05    BANGLORE             32          57     Rainy
5 2025-01-06    BANGLORE             33          59     Rainy
6 2025-01-07    BANGLORE             34          61     Sunny
7 2025-01-08    BANGLORE             32          63    Cloudy
8 2025-01-09  VIJAYAWADA             31          64     Rainy
9 2025-01-10  VIJAYAWADA             29          62     Sunny

In [60]:
df["City"] = df["City"].str.lower()
df

        Date        City  Temperature_C  Humidity_% Condition
0 2025-01-01    hyderbad             28          60     Sunny
1 2025-01-02    hyderbad             29          62     Sunny
2 2025-01-03    hyderbad             30          58    Cloudy
3 2025-01-04    hyderbad             31          55    Cloudy
4 2025-01-05    banglore             32          57     Rainy
5 2025-01-06    banglore             33          59     Rainy
6 2025-01-07    banglore             34          61     Sunny
7 2025-01-08    banglore             32          63    Cloudy
8 2025-01-09  vijayawada             31          64     Rainy
9 2025-01-10  vijayawada             29          62     Sunny

In [61]:
df["City"] = df["City"].str.replace("Hyderbad","chennai")
df

        Date        City  Temperature_C  Humidity_% Condition
0 2025-01-01    hyderbad             28          60     Sunny
1 2025-01-02    hyderbad             29          62     Sunny
2 2025-01-03    hyderbad             30          58    Cloudy
3 2025-01-04    hyderbad             31          55    Cloudy
4 2025-01-05    banglore             32          57     Rainy
5 2025-01-06    banglore             33          59     Rainy
6 2025-01-07    banglore             34          61     Sunny
7 2025-01-08    banglore             32          63    Cloudy
8 2025-01-09  vijayawada             31          64     Rainy
9 2025-01-10  vijayawada             29          62     Sunny